/*
-- Query: SELECT * FROM project3db.schools_table
LIMIT 0, 1000

-- Date: 2018-05-31 19:09
*/
INSERT INTO `schools_table` (`id`,`schoolcode`,`schoolname`,`location`,`enrollment`,`tuition`,`summary`,`photo`,`map`,`website`) VALUES (1,'ASUH','Arizona State University Havasu Campus','100 University Way Lake Havasu City, AZ 86403 ','1,800','$6,634 ','ASU@Lake Havasu, located in western Arizona on the California state line, is dedicated to immersive learning and collaboration between our students, faculty and community.','ASUHavasuPic','ASUHavasuMap','https://campus.asu.edu/havasu');
INSERT INTO `schools_table` (`id`,`schoolcode`,`schoolname`,`location`,`enrollment`,`tuition`,`summary`,`photo`,`map`,`website`) VALUES (2,'ASUP','Arizona State University Polytechnic Campus','7001 E Williams Field Road Mesa, AZ 85212','9,752','$10,552 ','The ASU Polytechnic campus is a nexus for studies in interdisciplinary sciences, engineering, management, technology and education. Industry partnerships are key to the campus’ distinctive course offerings, which provide opportunities for project-based learning within advanced laboratory spaces. ','ASUPolyPic','ASUPolyMap','https://campus.asu.edu/polytechnic');
INSERT INTO `schools_table` (`id`,`schoolcode`,`schoolname`,`location`,`enrollment`,`tuition`,`summary`,`photo`,`map`,`website`) VALUES (3,'ASUT','Arizona State University Tempe','Arizona State University Tempe, AZ 85281','51,869','$10,552 ','The historic ASU Tempe campus offers hundreds of majors that engage undergraduates and graduates in multidisciplinary research and exploration in first-rate laboratories and facilities.','ASUTempePic','ASUTempeMap','https://campus.asu.edu/tempe');
INSERT INTO `schools_table` (`id`,`schoolcode`,`schoolname`,`location`,`enrollment`,`tuition`,`summary`,`photo`,`map`,`website`) VALUES (4,'ASUW','Arizona State University West','4701 W Thunderbird Glendale, AZ 85306','3,663','$10,552 ','The West campus of Arizona State University creates a learning community blending liberal arts education with 21st-century workforce preparation','ASUWestPic','ASUWestMap','https://campus.asu.edu/west');
INSERT INTO `schools_table` (`id`,`schoolcode`,`schoolname`,`location`,`enrollment`,`tuition`,`summary`,`photo`,`map`,`website`) VALUES (5,'ASUX','Arizona State University Downtown Phoenix','411 N Central Ave Phoenix, AZ 85004','11,737','$10,552 ','Located in Arizona\'s capital, ASU\'S Downtown Phoenix campus provides a multitude of academic and professional connections for students preparing for multiple careers including health care, law, government, and journalism.','ASUPHXPic','ASUPHXMap','https://campus.asu.edu/downtown-phoenix');
INSERT INTO `schools_table` (`id`,`schoolcode`,`schoolname`,`location`,`enrollment`,`tuition`,`summary`,`photo`,`map`,`website`) VALUES (6,'NAUF','Northern Arizona University Flagstaff','S San Francisco St Flagstaff, AZ 86011','29,031','$11,564 ','Northern Arizona University (NAU) is a public higher-research university with a main campus at the base of the San Francisco Peaks in Flagstaff, Arizona, statewide campuses, and NAU Online.','NAUPic','NAUMap','https://nau.edu/');
INSERT INTO `schools_table` (`id`,`schoolcode`,`schoolname`,`location`,`enrollment`,`tuition`,`summary`,`photo`,`map`,`website`) VALUES (7,'UOFA','University of Arizona Tucson','The University of Arizona Tucson, AZ 85721','44,831','$11,877 ','The University of Arizona (also referred to as U of A, UA, or Arizona) is a public research university in Tucson, Arizona. Founded in 1885, the UA was the first university in the Arizona Territory.','UOFAPic','UOFAMap','http://arizona.edu/');
INSERT INTO `schools_table` (`id`,`schoolcode`,`schoolname`,`location`,`enrollment`,`tuition`,`summary`,`photo`,`map`,`website`) VALUES (8,'AZWC','Arizona Western College','2020 S Ave 8 E Yuma, AZ 85365','13,000','$2,400 ','Arizona Western College (AWC) is a public community college located in Yuma, Arizona, United States.','AZWesternPic','AZWesternMap','https://www.azwestern.edu/');
INSERT INTO `schools_table` (`id`,`schoolcode`,`schoolname`,`location`,`enrollment`,`tuition`,`summary`,`photo`,`map`,`website`) VALUES (9,'CAZC','Central Arizona College','8470 N Overfield Rd Coolidge, AZ 85128','7,442','$2,520 ','Central Arizona College (CAC) is a public community college located in Coolidge, Arizona. CAC serves the population of Pinal County.','AZCentralPic','AZCentralMap','https://centralaz.edu/');
INSERT INTO `schools_table` (`id`,`schoolcode`,`schoolname`,`location`,`enrollment`,`tuition`,`summary`,`photo`,`map`,`website`) VALUES (10,'CHSC','Cochise College','4190 AZ 80 Douglas, AZ 85607','5,585','$1,896 ','Cochise College is a public college in Arizona. Founded in 1964, the school has campuses in Douglas and Sierra Vista, and centers in Benson, Fort Huachuca, and Willcox.','CochisePic','CochiseMap','http://www.cochise.edu/');
INSERT INTO `schools_table` (`id`,`schoolcode`,`schoolname`,`location`,`enrollment`,`tuition`,`summary`,`photo`,`map`,`website`) VALUES (11,'CNOC','Coconino Community College','2800 S Lone Tree Rd Flagstaff, AZ 86005','5,641','$3,060 ','Coconino Community College (CCC) is a community college serving Coconino County in the northern part of the U.S. state of Arizona. CCC is a college that serves more than 7,500 learners annually','CoconinoPic','CoconinoMap','https://www.coconino.edu/');
INSERT INTO `schools_table` (`id`,`schoolcode`,`schoolname`,`location`,`enrollment`,`tuition`,`summary`,`photo`,`map`,`website`) VALUES (12,'EAZC','Eastern Arizona College','615 N Stadium Ave Thatcher, AZ 85552','6,799','$1,275 ','Eastern Arizona College (EAC), is a community college in Graham County, Arizona. The main campus is in Thatcher, with satellite locations in Gila County, and Greenlee County. It is the oldest community college in Arizona and the only community college in Arizona with a marching band.','EasternAZPic','EasternAZMap','http://www.eac.edu/');
INSERT INTO `schools_table` (`id`,`schoolcode`,`schoolname`,`location`,`enrollment`,`tuition`,`summary`,`photo`,`map`,`website`) VALUES (13,'CGCC','Chandler-Gilbert Community College','2626 E Pecos Rd Chandler, AZ 85225','14,030','$1,910 ','Chandler–Gilbert Community College(CGCC) is a community college in the Maricopa County Community College District founded in 1895 as an extension of Mesa Community College.','CGCCPic','CGCCMap','http://www.cgc.maricopa.edu/');
INSERT INTO `schools_table` (`id`,`schoolcode`,`schoolname`,`location`,`enrollment`,`tuition`,`summary`,`photo`,`map`,`website`) VALUES (14,'EMCC','Estrella Mountain Community College','3000 N Dysart Rd Avondale, AZ 85392','13,882','$2,064 ','Estrella Mountain Community College (EMCC) is a community college in Avondale, Arizona. The college has been serving the Southwest Valley community since 1990 and at the Avondale campus since 1992.','EMCCPic','EMCCMap','https://www.estrellamountain.edu/');
INSERT INTO `schools_table` (`id`,`schoolcode`,`schoolname`,`location`,`enrollment`,`tuition`,`summary`,`photo`,`map`,`website`) VALUES (15,'GWCC','GateWay Community College','108 N 40th St Phoenix, AZ 85034','16,000','$1,974 ','GateWay Community College is a community college in Phoenix, Arizona. Established in 1968, GateWay is one of ten regionally accredited colleges in the Maricopa County Community College District.','GWCCPic','GWCCMap','http://www.gatewaycc.edu/');
INSERT INTO `schools_table` (`id`,`schoolcode`,`schoolname`,`location`,`enrollment`,`tuition`,`summary`,`photo`,`map`,`website`) VALUES (16,'GDCC','Glendale Community College','6000 W Olive Ave Glendale, AZ 85302','19,000','$2,064 ','Glendale Community College (GCC) is a community college in Glendale, Arizona. GCC opened in 1965. Programs include associate degrees, certificate programs, industry-specific training and university transfer.','GCCPic','GCCMap','http://www.gccaz.edu/');
INSERT INTO `schools_table` (`id`,`schoolcode`,`schoolname`,`location`,`enrollment`,`tuition`,`summary`,`photo`,`map`,`website`) VALUES (17,'MSCC','Mesa Community College','1833 W Southern Ave Mesa, AZ 85202','20,424','$2,064 ','Mesa Community College (MCC) in Mesa, Arizona, is the largest of the 10 community colleges in the Maricopa County Community College District, which is the largest community college district in the United States in terms of enrollment.','MesaPic','MesaMap','http://www.mesacc.edu/');
INSERT INTO `schools_table` (`id`,`schoolcode`,`schoolname`,`location`,`enrollment`,`tuition`,`summary`,`photo`,`map`,`website`) VALUES (18,'PVCC','Paradise Valley Community College','18401 N 32nd St Phoenix, AZ 85032','9,477','$2,064 ','Paradise Valley Community College (PVCC) is a 2-year community college in northeastern Phoenix, Arizona, in the North Phoenix district. PVCC is located in Paradise Valley Village, one of the fifteen Urban Villages of Phoenix.','PVCCPic','PVCCMap','https://www.paradisevalley.edu/');
INSERT INTO `schools_table` (`id`,`schoolcode`,`schoolname`,`location`,`enrollment`,`tuition`,`summary`,`photo`,`map`,`website`) VALUES (19,'PHXC','Phoenix College','1202 W Thomas Rd Phoenix, AZ 85013','13,000','$2,064 ','Phoenix College, often referred to as simply PC, is a community college located in Encanto Village, Phoenix, Arizona, United States. Founded in 1920, it is one of the oldest community colleges in the country.','PHXPic','PHXMap','http://www.phoenixcollege.edu/');
INSERT INTO `schools_table` (`id`,`schoolcode`,`schoolname`,`location`,`enrollment`,`tuition`,`summary`,`photo`,`map`,`website`) VALUES (20,'RSDC','Rio Salado College','2323 W 14th St Tempe, AZ 85281','60,000','$2,064 ','Rio Salado College is a community collegeheadquartered in Tempe, Arizona. It is accredited by The Higher Learning Commissionof the North Central Association of Colleges and Schools and offers associate degree and certificate programs in online, in-person, and hybrid formats.','RioPic','RioMap','http://www.riosalado.edu/');
INSERT INTO `schools_table` (`id`,`schoolcode`,`schoolname`,`location`,`enrollment`,`tuition`,`summary`,`photo`,`map`,`website`) VALUES (21,'SDCC','Scottsdale Community College','9000 E Chaparral Rd Scottsdale, AZ 85256','3,748','$2,064 ','Scottsdale Community College, is located on the Salt River Pima-Maricopa Indian Community in Scottsdale, a suburb/rural area of Phoenix, Arizona. Scottsdale Community College is a two-year college located on the eastern boundary of the city of Scottsdale, Arizona, on 160 acres (650,000 m2) of land belonging to the Salt River Pima-Maricopa Indian Community.','SCCPic','SCCMap','http://www.scottsdalecc.edu/');
INSERT INTO `schools_table` (`id`,`schoolcode`,`schoolname`,`location`,`enrollment`,`tuition`,`summary`,`photo`,`map`,`website`) VALUES (22,'SMCC','South Mountain Community College','7050 S 24th St Phoenix, AZ 85042','4,738','$2,064 ','South Mountain Community College is a community college in Phoenix, Arizona. It is one of the ten colleges in the Maricopa County Community College District.','SMPic','SMMap','http://www.southmountaincc.edu/');
INSERT INTO `schools_table` (`id`,`schoolcode`,`schoolname`,`location`,`enrollment`,`tuition`,`summary`,`photo`,`map`,`website`) VALUES (23,'MHCC','Mohave Community College','480 S Central St Colorado City, AZ 86021','5,658','$1,944 ','Mohave Community College (also known as MCC) is a two-year, public community college with campuses in Kingman, Lake Havasu City, Bullhead City, and Colorado City, serving Mohave County, Arizona and the surrounding communities.','MohavePic','MohaveMap','http://www.mohave.edu/');
INSERT INTO `schools_table` (`id`,`schoolcode`,`schoolname`,`location`,`enrollment`,`tuition`,`summary`,`photo`,`map`,`website`) VALUES (24,'NLPC','Northland Pioneer College','1001 W Deuce of Clubs Show Low, AZ 85901','8,000','$1,680 ','Northland Pioneer College (NPC) is a regionally accredited, publicly supported, comprehensive community college serving a large and diverse area in Navajo County, Arizona.','NPCPic','NPCMap','http://www.npc.edu/');
INSERT INTO `schools_table` (`id`,`schoolcode`,`schoolname`,`location`,`enrollment`,`tuition`,`summary`,`photo`,`map`,`website`) VALUES (25,'PMCC','Pima Community College','4905 E Broadway Blvd Tucson, AZ 85709','30,082','$1,884 ','Pima Community College (PCC) is an American two-year institution of higher education in Pima County, Arizona serving the Tucson metropolitan area. The community college district consists of six campuses, four education centers, and several adult education learning centers.','PimaPic','PimaMap','http://www.pima.edu/');
INSERT INTO `schools_table` (`id`,`schoolcode`,`schoolname`,`location`,`enrollment`,`tuition`,`summary`,`photo`,`map`,`website`) VALUES (26,'YVPC','Yavapai College','1100 E Sheldon St Prescott, AZ 86301','8,197','$2,280 ','Yavapai College is a community collegelocated in Yavapai County, Arizona. The main campus is in Prescott, with locations in Clarkdale, Prescott Valley, Chino Valley, and Sedona.','YCPic','YCMap','http://www.yc.edu/');
